---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: s3-backup-cron
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 2
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: s3-backup-cron
              image: s3-backup:0.0.1
              imagePullPolicy: Never