apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "{{ .Values.extraConfigMapEnvVars.UPDATER_SCHEDULE }}"
  # How many completed jobs should be kept
  successfulJobsHistoryLimit: 1
  # We use concurrencyPolicy: Forbid to make sure that a new cronjob doesn't kill a previously started cronjob before it's completed
  # Here you can read about concurrencyPolicy: https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#concurrency-policy
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: {{ .Release.Name }}
              {{- if .Values.image.registry }}
              image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
              {{- else }}
              image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
              {{- end }}
              securityContext:
                privileged: true
              # resources:
              #   limits:
              #     cpu: {{ .Values.resources.limits.cpu }}
              #     memory: {{ .Values.resources.limits.memory }}
              #   requests:
              #     cpu: {{ .Values.resources.requests.cpu }}
              #     memory: {{ .Values.resources.requests.memory }}
              env:
                - name: DB_BACKUPS_FILENAME_PREFIX
                  value: {{ .Values.extraConfigMapEnvVars.DB_BACKUPS_FILENAME_PREFIX }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
          hostNetwork: true
