# Pelican local env, AGPL-3.0 license

repositories:
  - name: bitnami
    url: https://mirror.yandex.ru/helm/charts.bitnami.com
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: pelican-s3-backupper
    url: git+https://github.com/TourmalineCore/pelican-s3-backupper.git?ref=9338eb238a0daa3fd060b9bb6c945f6a9256a98c
  - name: pelican-db-backupper
    url: git+https://github.com/TourmalineCore/pelican-db-backupper.git?ref=7460d187fde973e0d80d330153aecabfeb623a3c
  - name: pelican-env-synchronizer
    url: git+https://github.com/TourmalineCore/pelican-env-synchronizer.git?ref=a5ce483f5943708049e3ca37c94bcd9155bf90bf

environments:
  local:
    values:
      - environments/{{ .Environment.Name }}/values.yaml.gotmpl

releases:
  - name: ingress-nginx
    labels:
      app: ingress-nginx
    wait: true
    chart: ingress-nginx/ingress-nginx
    # update ingress-nginx version to 1.12.1 for fix CVE-2025-1098
    # https://www.opennet.ru/opennews/art.shtml?num=62946
    version: 4.12.1
    values:
      - values-ingress-nginx.yaml.gotmpl

  - name: postgresql
    namespace: default
    labels:
      app: postgresql
    wait: true
    chart: bitnami/postgresql
    version: 12.2.7
    values:
      - values-postgre.yaml.gotmpl

  - name: minio-s3
    labels:
      app: minio-s3
    wait: true
    chart: bitnami/minio
    version: 14.8.5
    values: 
      - values-minio.yaml.gotmpl

  - name: pelican-ui
    labels:
      app: pelican-ui
    wait: true
    chart: bitnami/nginx
    # after 15.3.5 our docker file or setup can no longer start, need to investigate what is wrong for the newer versions
    version: 15.3.5
    # it won't work anyway until ingress controller is created
    # thus we wait for it to be ready first
    needs: 
      - ingress-nginx
    values:
      # https://helmfile.readthedocs.io/en/latest/#loading-remote-environment-values-files
      - git::https://github.com/TourmalineCore/pelican-ui.git@/ci/values.yaml?ref=6297aa1c297f7de07b7734fdbf624128333fa26d
      - values.yaml.gotmpl
      - values-ui.yaml.gotmpl

  - name: pelican-cms
    labels:
      app: pelican-cms
    wait: true
    chart: bitnami/nginx
    # after 15.3.5 our docker file or setup can no longer start, need to investigate what is wrong for the newer versions
    version: 15.3.5
    # it won't work anyway until ingress controller is created
    # thus we wait for it to be ready first
    needs: 
      - ingress-nginx
      - postgresql
    values:
      # https://helmfile.readthedocs.io/en/latest/#loading-remote-environment-values-files
      - git::https://github.com/TourmalineCore/pelican-cms.git@/ci/values.yaml?ref=b995d6cc2fd483d2b5c3956fa2b6e90ff875ea88
      - values.yaml.gotmpl
      - values-cms.yaml.gotmpl

  - name: pelican-s3-backupper
    labels:
      app: pelican-s3-backupper
    wait: true
    chart: pelican-s3-backupper/pelican-s3-backupper
    needs: 
      - minio-s3
    values:
      # https://helmfile.readthedocs.io/en/latest/#loading-remote-environment-values-files
      - git::https://github.com/TourmalineCore/pelican-s3-backupper.git@/ci/values.yaml?ref=9338eb238a0daa3fd060b9bb6c945f6a9256a98c
      - values.yaml.gotmpl
      - values-pelican-s3-backupper.yaml.gotmpl

  - name: pelican-db-backupper
    labels:
      app: pelican-db-backupper
    wait: true
    chart: pelican-db-backupper/pelican-db-backupper
    needs: 
      - minio-s3
      - postgresql
    values:
      # https://helmfile.readthedocs.io/en/latest/#loading-remote-environment-values-files
      - git::https://github.com/TourmalineCore/pelican-db-backupper.git@/ci/values.yaml?ref=7460d187fde973e0d80d330153aecabfeb623a3c
      - values.yaml.gotmpl
      - values-pelican-db-backupper.yaml.gotmpl

  - name: pelican-env-synchronizer
    labels:
      app: pelican-env-synchronizer
    wait: true
    chart: pelican-env-synchronizer/pelican-env-synchronizer
    values:
      # https://helmfile.readthedocs.io/en/latest/#loading-remote-environment-values-files
      - git::https://github.com/TourmalineCore/pelican-env-synchronizer.git@/ci/values.yaml?ref=a5ce483f5943708049e3ca37c94bcd9155bf90bf
      - values.yaml.gotmpl
      - values-pelican-env-synchronizer.yaml.gotmpl
