apiVersion: v1
kind: Secret
metadata:
  name: pgsql-backup-secret
  namespace: local
type: Opaque
stringData:
    PG_HOST: "postgresql"
    PG_PASSWORD: "admin"
    PG_USER: "postgres"
    PG_DATABASE: "pelican_db"
    AWS_ACCESS_KEY_ID: "pUEqgxgOcfbYtjjIKh9O"
    AWS_SECRET_ACCESS_KEY: "ea3d5VmkMGxUKvXc8JXgPE3g1IXa9cp6V47JkAZF"
    AWS_BUCKET_NAME: "pelican-db-backup"
    AWS_HOST: "http://minio-s3:9000"
