name: E2E Tests Execution Against Local Env

on:
  push:
    branches:
      - feature/*

jobs:
  run-e2e-against-local-env:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout Local Env
      uses: actions/checkout@v4

    - name: Deploy Local Env to Kind k8s
      uses: devcontainers/ci@v0.3
      with:
        runCmd: |
          kind create cluster --name pelican --config kind-local-config.yaml --kubeconfig ./.pelican-cluster-kubeconfig

          # we need to overrive backup schedule of backuppers inside local-env to run cronjob every minute 
          sed -i "0,/BACKUPS_SCHEDULE:.*/s//BACKUPS_SCHEDULE: \"*\/1 * * * *\"/" deploy/values-pelican-db-backupper.yaml.gotmpl
          sed -i "0,/BACKUPS_SCHEDULE:.*/s//BACKUPS_SCHEDULE: \"*\/1 * * * *\"/" deploy/values-pelican-s3-backupper.yaml.gotmpl
          
          helmfile cache cleanup && helmfile --environment local --namespace local -f deploy/helmfile.yaml apply
        # we don't need to push docker image that was built using our Dev Container
        push: never

    # PLAYWRIGHT UI TESTS

    - name: Checkout Pelican UI
      uses: actions/checkout@v4
      with:
        repository: TourmalineCore/pelican-ui
        # we need to specify this path otherwise it will create this folder pelican-local-env/pelican-local-env
        # and that will lead to permissions error at the next CMS repo checkout when it tries to remove no longer needed folder
        # this path that matches the repo name isolates UI src folder from CMS one
        path: pelican-ui

    - name: Playwright Run Against UI
      uses: devcontainers/ci@v0.3
      with:
        subFolder: pelican-ui
        # we expect that UI repo as well as CMS one contains the needed Dev Container configuration
        # that allows us to get rid of caching and installation of deps here and rely of docker images more
        configFile: ./pelican-ui/.devcontainer/e2e-tests-in-pr/devcontainer.json
        # we use --reporter=list to prints a line for each test being run
        # https://playwright.dev/docs/test-reporters#list-reporter
        runCmd: |
          npx playwright test --reporter=list,html --config=playwright.e2e.config.ts
        # we don't need to push docker image that was built using our Dev Container
        push: never
        # we forward CI env var value from GitHub to Dev Container
        # without it CI is not defined
        # We set the PLAYWRIGHT_HTML_OPEN flag to never to avoid opening the HTML report if the test fails
        # https://playwright.dev/docs/test-reporters#html-reporter 
        env: |
          PLAYWRIGHT_HTML_OPEN=never
          FRONTEND_URL=http://localhost:40110 
          API_URL=http://localhost:40110/cms/api
          CMS_URL=http://localhost:40110/cms
          CI

    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: html-report--attempt-${{ github.run_attempt }}
        path: pelican-ui/playwright-report
        retention-days: 7

    # PLAYWRIGHT CMS TESTS

    - name: Checkout Pelican CMS
      uses: actions/checkout@v4
      with:
        repository: TourmalineCore/pelican-cms
        path: pelican-cms

    - name: Playwright Run Against CMS
      uses: devcontainers/ci@v0.3
      with:
        subFolder: pelican-cms
        configFile: ./pelican-cms/.devcontainer/e2e-tests-in-pr/devcontainer.json
        runCmd: |
          npx playwright test --reporter=html
        push: never
        env: |
          PLAYWRIGHT_HTML_OPEN=never
          FRONTEND_URL=http://localhost:40110
          SERVER_URL=http://localhost:40110/cms

    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: html-report--attempt-${{ github.run_attempt }}
        path: pelican-cms/playwright-report
        retention-days: 7

    # DB BACKUPPER E2E TESTS

    - name: Checkout Pelican DB backupper
      uses: actions/checkout@v4
      with:
        repository: TourmalineCore/pelican-db-backupper
        path: pelican-db-backupper

    - name: Run DB backupper E2E tests
      run: python ./pelican-db-backupper/e2e-tests.py
      env: 
        DB_AWS_ACCESS_KEY_ID: admin
        DB_AWS_SECRET_ACCESS_KEY: rootPassword
        DB_AWS_ENDPOINT: http://minio-s3.localhost:40110
        DB_AWS_BUCKET_NAME: pelican-backups
        DB_BACKUPS_FILENAME_PREFIX: pelican-local-env-db

    # S3 BACKUPPER E2E TESTS
    - name: Write creds for aws tool 
      run: |
        mkdir ~/.aws
        echo "[default]" | tee ~/.aws/credentials             
        echo "aws_access_key_id = admin" | tee -a ~/.aws/credentials             
        echo "aws_secret_access_key = rootPassword" | tee -a ~/.aws/credentials

    - name: Upload test file to S3
      run: |
        echo "test" > test.txt
        aws --endpoint-url http://minio-s3.localhost:40110 s3 cp ./test.txt s3://pelican-local-env
        
    # Wait 60 seconds to make sure that backup was created
    - name: Wait 60 seconds
      run: sleep 60

    - name: Checkout Pelican S3 backupper
      uses: actions/checkout@v4
      with:
        repository: TourmalineCore/pelican-s3-backupper
        path: pelican-s3-backupper

    - name: Run S3 backupper E2E tests
      run: python ./pelican-s3-backupper/e2e-tests.py
      env: 
        S3_AWS_ACCESS_KEY_ID: admin
        S3_AWS_SECRET_ACCESS_KEY: rootPassword
        S3_AWS_ENDPOINT: http://minio-s3.localhost:40110
        S3_AWS_BUCKET_NAME: pelican-backups
        S3_BACKUPS_FILENAME_PREFIX: pelican-local-env-s3
