name: E2E Tests Execution Against Local Env

on:
  push:
    branches:
      - feature/e2e-tests

jobs:
  run-e2e-against-local-env:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout Local Env
      uses: actions/checkout@v4

    - name: Deploy Local Env to Kind k8s
      uses: devcontainers/ci@v0.3
      with:
        runCmd: |
          kind create cluster --name pelican --config kind-local-config.yaml --kubeconfig ./.pelican-cluster-kubeconfig
          helmfile cache cleanup && helmfile --environment local --namespace local -f deploy/helmfile.yaml apply
        # we don't need to push docker image that was built using our Dev Container
        push: never


    # PLAYWRIGHT UI TESTS

    - name: Checkout Pelican UI
      uses: actions/checkout@v4
      with:
        repository: TourmalineCore/pelican-ui
        ref: feature/e2e-tests-in-pr-dev-container
        path: pelican-ui

    - name: Playwright run for UI
      uses: devcontainers/ci@v0.3
      with:
        configFile: ./.devcontainer/e2e-tests-in-pr/devcontainer.json
        runCmd: |
          npx playwright test --reporter=html --config=playwright.e2e.config.ts
        # we don't need to push docker image that was built using our Dev Container
        push: never
        env: |
          FRONTEND_URL=http://localhost:40110 
          API_URL=http://localhost:40110/cms/api

    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: html-report--attempt-${{ github.run_attempt }}
        path: playwright-report
        retention-days: 7

    # PLAYWRIGHT CMS TESTS

    - name: Checkout Pelican CMS
      uses: actions/checkout@v4
      with:
        repository: TourmalineCore/pelican-cms
        ref: feature/e2e-tests-in-pr-dev-container
        path: pelican-cms

    - name: Playwright run for CMS
      uses: devcontainers/ci@v0.3
      with:
        configFile: ./.devcontainer/e2e-tests-in-pr/devcontainer.json
        runCmd: |
          npx playwright test --reporter=html
        # we don't need to push docker image that was built using our Dev Container
        push: never
        env: |
          FRONTEND_URL=http://localhost:40110
          SERVER_URL=http://localhost:40110/cms

    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: html-report--attempt-${{ github.run_attempt }}
        path: playwright-report
        retention-days: 7
