name: E2E Tests Execution Against Local Env

on:
  push:
    branches:
      - feature/*

jobs:
  run-e2e-against-local-env:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Local Env
      uses: actions/checkout@v4

    - name: Deploy Local Env to Kind k8s
      uses: devcontainers/ci@v0.3
      with:
        runCmd: |
          kind create cluster --name pelican --config kind-local-config.yaml --kubeconfig ./.pelican-cluster-kubeconfig
          helmfile cache cleanup && helmfile --environment local --namespace local -f deploy/helmfile.yaml apply
        # we don't need to push docker image that was built using our Dev Container
        push: never

    # CYPRESS UI TESTS

    - name: Checkout Pelican UI
      uses: actions/checkout@v4
      with:
        repository: TourmalineCore/pelican-ui

    # currently there's a risk that when we run this step the cluster is already destroyed since it was created in a previous step
    # for the sake of simlicity it is kept like this here
    # however, in production with longer pipelines: more services and more tests it will most likely start causing issues
    # creation of the cluster and deployment to it should be in the same step as the e2e tests running 
    - name: Playwright Run Against Pelican UI
      uses: microsoft/playwright-github-action@v1.5.6
      with:
        config-file: playwright.config.ts

    # CYPRESS CMS TESTS

    - name: Checkout Pelican CMS
      uses: actions/checkout@v4
      with:
        repository: TourmalineCore/pelican-cms

    - name: Playwright Run Against Pelican CMS
      uses: microsoft/playwright-github-action@v1.5.6
      with:
        config-file: playwright.config.ts

    # KARATE CMS TESTS

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
      
    - name: Download Karate JAR
      run: |
        curl -L https://github.com/karatelabs/karate/releases/download/v1.5.1/karate-1.5.1.jar -o karate.jar
       
    - name: Karate Run Against Pelican CMS
      run: |
        java -jar karate.jar .
      env:
        AUTH_API_ROOT_URL: "http://localhost:30090/api/auth"
        API_ROOT_URL: "http://localhost:30090/api"
        AUTH_LOGIN: "ceo@tourmalinecore.com"
        AUTH_PASSWORD: "cEoPa$$wo1d"
        SHOULD_USE_FAKE_EXTERNAL_DEPENDENCIES: "false"