name: Sync services
on: 
  repository_dispatch:

jobs:
  Sync-services:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Local Env  
        uses: actions/checkout@v3 
        with:
          token: ${{ secrets.PELICAN_ENV_SYNC_TRIGGER_TOKEN }}

      - name: Set branch name
        run: 
          echo "BRANCH_NAME=feature/sync-image-tag-${{ github.event.client_payload.repository }}-$(date +'%FT%H-%M')-short-sha-${{ github.event.client_payload.short_sha }}" >> $GITHUB_ENV

        # We tried to use yq to change the image tag, but at values for cms we have non-yaml code that yq can`t parse or ignore
        # so for that reason we use Stream EDitor which can find needeed string using regular expressions and change it to a new value
      - name: Write new UI image tag to values
        run: |
          sed "0,/tag:.*/s//tag: \"local-env-sha-${{ github.event.client_payload.sha }}\"/" deploy/values-ui.yaml.gotmpl >  deploy/values-ui.yaml.gotmpl.2
          cp deploy/values-ui.yaml.gotmpl.2 deploy/values-ui.yaml.gotmpl

      - name: Commit and Push Changes
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com

          git checkout -b $BRANCH_NAME master

          git add deploy/values-ui.yaml.gotmpl

          git commit -m "${{ github.event.client_payload.commit_message }}"
          
          git push origin $BRANCH_NAME

      - name: Set PR title
        run: 'echo "PR_TITLE=sync: ${{ github.event.client_payload.repository }} image tag" >> $GITHUB_ENV' 
        
      - name: Create PR
        run: gh pr create -B master -H $BRANCH_NAME --title "${{ env.PR_TITLE }}" --body "${{ github.event.client_payload.commit_message }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
